volumes:
  prometheus_storage:


services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_storage:/prometheus
